services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.21
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: finance_payment
      MYSQL_ROOT_PASSWORD: googolplex10100!
      MYSQL_USER: finance_payment
      MYSQL_PASSWORD: "Fp_2026_Secure!"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app

volumes:
  mysql-data:

networks:
  app:
    driver: bridge
